resource_types:
  - name: merge-request
    type: docker-image
    source:
      repository: samcontesse/gitlab-merge-request-resource

resources:
  - name: merge-request
    type: merge-request
    icon: gitlab
    source:
      uri: https://gitlab.com/blackrockllc/front.git
      private_token: ((gitlab.private-token))

jobs:
  - name: run-tests
    plan:
      - get: merge-request
        trigger: true
      - put: merge-request
        params:
          repository: merge-request
          status: running
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: node
              tag: 13-alpine
          inputs:
            - name: merge-request
          run:
            path: /bin/sh
            args:
              - -xec
              - |
                cd merge-request
                yarn install
                yarn test
          params:
            CI: 'true'
        on_failure:
          put: merge-request
          params:
            repository: merge-request
            status: failed
        on_success:
          put: merge-request
          params:
            repository: merge-request
            status: success
